apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "br10",
      "plugins": [
          {
              "type": "bridge",
              "bridge": "br10"
          },
          {
              "type": "tuning"
          }
      ]
    }