---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-vm-latency-checkup
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-vm-latency-checkup-results
  namespace: kubevirt-vm-latency-checkup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-vm-latency-checkup
  namespace: kubevirt-vm-latency-checkup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-patcher
  namespace: kubevirt-vm-latency-checkup
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "patch" ]
    resourceNames: ["kubevirt-vm-latency-checkup-results"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-patcher-kubevirt-vm-latency-checkup-sa
  namespace: kubevirt-vm-latency-checkup
subjects:
  - kind: ServiceAccount
    name: kubevirt-vm-latency-checkup-sa
    namespace: kubevirt-vm-latency-checkup
roleRef:
  kind: Role
  name: configmap-patcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-vmis-manager
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/console"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-vmis-manager
subjects:
- kind: ServiceAccount
  name: kubevirt-vm-latency-checkup
  namespace: kubevirt-vm-latency-checkup
roleRef:
  kind: ClusterRole
  name: kubevirt-vmis-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubevirt-vm-latency-checkup
  namespace: kubevirt-vm-latency-checkup
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kubevirt-vm-latency-checkup
      containers:
        - name: vmlatency
          image: quay.io/kiagnose/kubevirt-vm-latency:devel
          env:
            - name: RESULT_CONFIGMAP_NAMESPACE
              value: "kubevirt-vm-latency-checkup"
            - name: RESULT_CONFIGMAP_NAME
              value: "kubevirt-vm-latency-checkup-results"
            - name: NETWORK_ATTACHMENT_DEFINITION_NAME
              value: "bridge-network"
            - name: NETWORK_ATTACHMENT_DEFINITION_NAMESPACE
              value: "default"
            - name: SAMPLE_DURATION_SECONDS
              value: "30"
            - name: MAX_DESIRED_LATENCY_MILLISECONDS
              value: "100"
            - name: SOURCE_NODE
              value: ""
            - name: TARGET_NODE
              value: ""
