---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-checkup-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-checkup-results
  namespace: echo-checkup-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-checkup-sa
  namespace: echo-checkup-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-patcher
  namespace: echo-checkup-ns
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "patch" ]
    resourceNames: ["echo-checkup-results"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-patcher-echo-checkup-sa
  namespace: echo-checkup-ns
subjects:
  - kind: ServiceAccount
    name: echo-checkup-sa
    namespace: echo-checkup-ns
roleRef:
  kind: Role
  name: configmap-patcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: echo-checkup
  namespace: echo-checkup-ns
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: echo-checkup-sa
      containers:
        - name: echo
          image: echo-checkup:devel
          env:
            - name: RESULT_CONFIGMAP_NAMESPACE
              value: echo-checkup-ns
            - name: RESULT_CONFIGMAP_NAME
              value: echo-checkup-results
            - name: MESSAGE
              value: Hi!
      restartPolicy: Never
...
