name: checkup-echo.checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run unit tests
        working-directory: ./checkups/echo
        run: ./automation/make.sh --unit-test
  e2e-test:
    name: e2e
    runs-on: ubuntu-latest
    env:
      KIND: /usr/local/bin/kind
      KUBECTL: /usr/local/bin/kubectl
      CRI: docker
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build kiagnose image
        run: ./automation/make.sh --build-core --build-core-image
      - name: Deploy
        run: ./automation/make.sh --e2e -- --install-kind --install-kubectl --create-cluster --deploy-kiagnose
      - name: Run e2e tests
        run: ./automation/make.sh --e2e -- --run-tests
      - name: Delete cluster
        run: ./automation/make.sh --e2e -- --delete-cluster
