name: checkup-echo.publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./checkups/echo

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ECHO_IMAGE_TAG: main
      CRI: podman
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Logging to quay.io
        run:
          ${CRI} login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Build and push images
        run: |
          ./automation/make.sh \
            --build-checkup-image \
            --push-checkup-image
