name: checkup-kubevirt-vm-latency.publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CHECKUP_IMAGE_TAG: main
      CRI: podman
      CHECKUP: kubevirt-vm-latency
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: arnested/go-version-action@v1
        id: go-version
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
      - name: Logging to quay.io
        run: 
          ${CRI} login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Build and push images
        working-directory: checkups/${{ env.CHECKUP }}
        run: |
          ./automation/make.sh \
            --build-checkup \
            --build-checkup-image \
            --push-checkup-image
