name: publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      minimal: ${{ steps.versions.outputs.minimal }}
    steps:
      - uses: actions/checkout@v2
      - uses: arnested/go-version-action@v1
        id: versions
  publish:
    runs-on: ubuntu-latest
    needs: go-versions
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-versions.outputs.minimal }}
      - name: Build binary and core image
        env:
          CORE_IMAGE_TAG: main
        run: ./automation/make.sh --build-core --build-core-image
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io
      - name: Push to quay.io
        run: podman push quay.io/kiagnose/kiagnose:main
