name: publish

on:
  push:
    branches:
    - main
    tags:
    - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
      minimal: ${{ steps.versions.outputs.minimal }}
    steps:
      - uses: actions/checkout@v2
      - uses: arnested/go-version-action@v1
        id: versions
  publish:
    runs-on: ubuntu-latest
    needs: go-versions
    env:
      CORE_IMAGE_TAG: ${{github.ref_name}}
      CRI: podman
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-versions.outputs.minimal }}
      - name: Logging to quay.io
        run: 
          ${CRI} login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Build and push images
        run: |
          ./automation/make.sh \
            --build-core \
            --build-core-image \
            --push-core-image
